name: Test

on:
  release:
    types: [published]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create test environment file
      run: |
        echo "# Test Environment Variables for ServerManager Tests" > tests/.test.env
        echo "WEBHOOK_SECRET=test-webhook-secret-123" >> tests/.test.env
        echo "WEBHOOK_PORT=3007" >> tests/.test.env
        echo "PM2_NAME=test-community-server" >> tests/.test.env
        echo "BEARER_TOKEN__0=test-avalanche-token" >> tests/.test.env
        echo "BEARER_TOKEN__1=test-agentpays-token" >> tests/.test.env
        echo "BEARER_TOKEN__2=test-lukso-token" >> tests/.test.env
        echo "BEARER_TOKEN__3=test-chainlink-token" >> tests/.test.env
        echo "ACCOUNT_DEVELOPMENT2_PRIVATE_KEY=0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12" >> tests/.test.env
        echo "ACCOUNT_DEVELOPMENT2_PUBLIC_KEY=0x742d35Cc6634C0532925a3b8D6aC6782d3B5C123" >> tests/.test.env
        echo "BASE_SEPOLIA_ALCHEMY_HTTP=https://base-sepolia.g.alchemy.com/v2/test-api-key-12345" >> tests/.test.env
    
    - name: Create development test environment file
      run: |
        echo "# Development Test Environment" > tests/.community.env
        echo "SERVER_URL=http://localhost" >> tests/.community.env
        echo "SERVER_PORT=3000" >> tests/.community.env
        echo "WEBHOOK_SECRET=dev_webhook_secret_123" >> tests/.community.env
        echo "WEBHOOK_PORT=3001" >> tests/.community.env
        echo "PM2_NAME=community-server-dev" >> tests/.community.env
    
    - name: Run tests with coverage
      run: npm run test:coverage:src
      env:
        NODE_OPTIONS: '--experimental-vm-modules'
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false